name = "ManyExpertDecisionTrees"
uuid = "b59e7f69-5672-4a63-bb58-b897b1454099"
version = "1.0.0"
authors = ["Alberto Paparella", "Alexandr Sapogovski"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
FuzzyLogic = "271df9f8-4390-4196-9d4f-bdd0b67035b3"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataFrames = "1.8.1"
DecisionTree = "0.12.4"
FuzzyLogic = "0.1.3"
SoleLogics = "0.13.2"
Statistics = "1.10.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
